api:
  name: Steam Common Games Finder
  host: 'localhost'
  port: 3773
  debug: true
  test_mode: 'true'
  base_url: 'http://localhost:3773'
  log:
    json: 'false'
    opsInterval: 30000
    console:
      level: 'info'
  http:
    cache:
      maxAge: 60000
secrets:
  steam_api_url: 'https://api.steampowered.com' 